# Generated by Django 3.2.6 on 2021-09-26 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividadeconomica',
            fields=[
                ('id_actividadeconomica', models.AutoField(max_length=16, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.AutoField(max_length=16, primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(max_length=16, primary_key=True, serialize=False)),
                ('dni_empresa', models.CharField(max_length=45)),
                ('nombre_comercial', models.CharField(max_length=60)),
                ('razon_social', models.CharField(max_length=60)),
                ('calle_principal', models.CharField(max_length=60)),
                ('calle_secundaria', models.CharField(max_length=60)),
                ('manzana', models.CharField(max_length=20)),
                ('villa', models.CharField(max_length=20)),
                ('referencia', models.CharField(max_length=60)),
                ('telefono_oficina', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=60)),
                ('pagina_web', models.CharField(max_length=60)),
                ('actividad_economica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWeb.actividadeconomica')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWeb.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Estadocivil',
            fields=[
                ('id_estadocivil', models.AutoField(max_length=16, primary_key=True, serialize=False)),
                ('estado_civil', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Estadocuenta',
            fields=[
                ('id_estadocuenta', models.AutoField(max_length=16, primary_key=True, serialize=False)),
                ('estado_cuenta', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(max_length=16, primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_provincia', models.AutoField(max_length=16, primary_key=True, serialize=False)),
                ('provincia', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Ramaactividad',
            fields=[
                ('id_ramaactividad', models.AutoField(max_length=16, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(max_length=16, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id_sector', models.AutoField(max_length=16, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Tipodocumento',
            fields=[
                ('id_tipodocumento', models.AutoField(max_length=16, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Tipoempresa',
            fields=[
                ('id_tipoempresa', models.AutoField(max_length=16, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Tipopersona',
            fields=[
                ('id_tipopersona', models.AutoField(max_length=16, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(max_length=16, primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=45)),
                ('contrasenia', models.CharField(max_length=16)),
                ('cedula', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('correo', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=80)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWeb.ciudad')),
                ('estado_civil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWeb.estadocivil')),
                ('estado_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWeb.estadocuenta')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWeb.genero')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWeb.rol')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWeb.provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id_representante', models.AutoField(max_length=16, primary_key=True, serialize=False)),
                ('estado_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWeb.estadocuenta')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWeb.empresa')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWeb.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWeb.provincia'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='rama_actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWeb.ramaactividad'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWeb.sector'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWeb.tipodocumento'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWeb.tipoempresa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWeb.tipopersona'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='id_provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWeb.provincia'),
        ),
    ]
